ROLE_CUSTOMER = "customer"
ROLE_ENGINEER = "engineer"
ROLE_ADMIN = "admin"

TICKET_STATUS_OPEN = "open"
TICKET_STATUS_ASSIGNED = "assigned"
TICKET_STATUS_RESOLVED = "resolved"

ASSIGNMENT_STATUS_ASSIGNED = "assigned"
ASSIGNMENT_STATUS_COMPLETED = "completed"

NETWORK_STATUS_ACTIVE = "active"
NETWORK_STATUS_DOWN = "down"
NETWORK_STATUS_MAINTENANCE = "maintenance"

ISSUE_TYPE_NO_SIGNAL = "no_signal"
ISSUE_TYPE_SLOW_INTERNET = "slow_internet"
